name: constants
description: Common constant values used by many ODW packages
version: 0.7.6
homepage: https://github.com/OpenDICOMweb/constants
author: JamesPhilbin <jfphilbin@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  charcode: any

dev_dependencies:
  test: ^1.6.0
